name: Deploy to itch.io

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install and publish with butler
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          wget https://broth.itch.ovh/butler/linux-amd64/butler.zip
          unzip butler.zip
          zip -r dist.zip .
          ./butler push dist.zip Unloosed/test-project:html --userversion 0.0.1
